CREATE TABLE `approval_requests` (
  `id` VARCHAR(80) NOT NULL,
  `run_id` CHAR(36) NULL,
  `task_id` CHAR(36) NULL,
  `tool_call_id` VARCHAR(160) NOT NULL,
  `tool_name` VARCHAR(120) NOT NULL,
  `args_redacted` JSON NULL,
  `risk` VARCHAR(40) NOT NULL,
  `reason` TEXT NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `requested_at` DATETIME(3) NOT NULL,
  `expires_at` DATETIME(3) NULL,
  `decided_at` DATETIME(3) NULL,
  `decided_by` VARCHAR(120) NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `approval_requests_status_requested_idx` (`status`, `requested_at`),
  INDEX `approval_requests_run_id_idx` (`run_id`),
  INDEX `approval_requests_task_id_idx` (`task_id`),
  INDEX `approval_requests_tool_call_id_idx` (`tool_call_id`),
  CONSTRAINT `approval_requests_run_id_fkey` FOREIGN KEY (`run_id`) REFERENCES `harness_runs`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `approval_requests_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `harness_tasks`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
